"""Gettext extraction for deterministic analytics labels and workflow states."""
from django.utils.translation import gettext_noop as _

LABELS = [
    _('Arithmetic mean of recorded working-set RPE.'),
    _('Average frequency'),
    _('Count distinct active workout IDs.'),
    _('Count distinct local start dates.'),
    _('Count each working set once for each listed secondary muscle.'),
    _('Count each working set once for its primary muscle.'),
    _('Count normal, failure, and dropset sets with a compatible metric.'),
    _('Count sets by recorded type.'),
    _('Count working sets by recorded RPE.'),
    _('Count workout-set rows.'),
    _('Count workouts by local calendar bucket.'),
    _('Count workouts by local weekday.'),
    _('Duration'),
    _('Executed primary-muscle sets'),
    _('Executed secondary-muscle coverage'),
    _('External-load volume'),
    _('Mean RPE'),
    _('Median RPE'),
    _('Median of recorded working-set RPE.'),
    _('Missing RPE'),
    _('RPE'),
    _('RPE distribution'),
    _('Set-type counts'),
    _('Sum and arithmetic mean of end_time - start_time.'),
    _('Sum non-null repetitions on rep-based templates.'),
    _('Target completion'),
    _('Total repetitions'),
    _('Total sets'),
    _('Training days'),
    _('Weekday distribution'),
    _('Working sets'),
    _('Workouts'),
    _('Workouts by period'),
    _('associations'),
    _('completed sessions / weekly target.'),
    _('conflict'),
    _('count/percent'),
    _('create'),
    _('days'),
    _('expired'),
    _('failed'),
    _('kg·rep'),
    _('not_executed'),
    _('partial'),
    _('previewed'),
    _('ratio/percent'),
    _('reps'),
    _('seconds'),
    _('sessions/week'),
    _('sets'),
    _('sets/percent'),
    _('submitting'),
    _('succeeded'),
    _('unknown'),
    _('update'),
    _('working sets without RPE / all working sets.'),
    _('workouts'),
    _('workouts / inclusive_days × 7'),
    _('Σ(weight_kg × reps).'),
]
