# Generated by Django 6.0.8 on 2026-08-29 21:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('weekly_session_target', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mass_unit', models.CharField(choices=[('kg', 'Quilogramas'), ('lb', 'Libras')], default='kg', max_length=2)),
                ('distance_unit', models.CharField(choices=[('km', 'Quilômetros'), ('mi', 'Milhas')], default='km', max_length=2)),
                ('snapshot_retention_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
