# Generated by Django 6.0.8 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ownerpreference_snapshot_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpreference',
            name='date_format',
            field=models.CharField(choices=[('DMY', 'DD/MM/YYYY'), ('MDY', 'MM/DD/YYYY')], default='DMY', max_length=3),
        ),
    ]
