# Generated by Django 6.0.8 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ownerpreference_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpreference',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Kilometres'), ('mi', 'Miles')], default='km', max_length=2),
        ),
        migrations.AlterField(
            model_name='ownerpreference',
            name='mass_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2),
        ),
    ]
