# Generated by Django 6.0.8 on 2026-08-29 21:52

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HevyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('verified_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hevy_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=16)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('last_success_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('last_full_refresh_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('last_incremental_run_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('is_stale', models.BooleanField(default=True)),
                ('hevy_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_state', to='integrations.hevyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('overlap_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='integrations.hevyaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hevy_account', 'stream_name'), name='unique_sync_cursor_stream')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('plans', 'Plans'), ('validate', 'Validate')], max_length=16)),
                ('trigger', models.CharField(choices=[('web', 'Web'), ('command', 'Command'), ('schedule', 'Schedule'), ('retry', 'Retry')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('finished_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('item_counts', models.JSONField(blank=True, default=dict)),
                ('page_counts', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('cursor_before', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('cursor_after', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('sanitized_error', models.CharField(blank=True, max_length=500)),
                ('adapter_version', models.CharField(blank=True, max_length=32)),
                ('application_version', models.CharField(blank=True, max_length=32)),
                ('provider_schema_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.hevyaccount')),
                ('prior_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='integrations.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['hevy_account', 'state', 'started_at'], name='sync_run_account_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='sync_run_valid_time_range')],
            },
        ),
    ]
