# Generated by Django 6.0.8 on 2026-09-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_routinewriteintent_sync_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hevyaccount',
            name='credential_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hevyaccount',
            name='encrypted_api_key',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='integrationstate',
            name='last_catalog_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationstate',
            name='last_plans_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationstate',
            name='next_auto_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProviderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=32)),
                ('pages', models.JSONField(default=list)),
                ('synced_at', models.DateTimeField()),
                ('source_hash', models.CharField(max_length=64)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='integrations.hevyaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hevy_account', 'resource'), name='unique_provider_snapshot')],
            },
        ),
    ]
