# Generated by Django 6.0.8 on 2026-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_hevyaccount_credential_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routinewriteintent',
            name='routine_intent_state_idx',
        ),
        migrations.DeleteModel(
            name='RoutineWriteIntent',
        ),
    ]
