# Generated by Django 6.0.8 on 2026-08-29 21:57

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_created_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('external_updated_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('provider_schema_version', models.CharField(max_length=32)),
                ('source_payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Payload hash must be a 64-character SHA-256 hex value.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('exercise_type', models.CharField(choices=[('weight_reps', 'Weight and reps'), ('reps_only', 'Reps only'), ('bodyweight_reps', 'Bodyweight reps'), ('bodyweight_assisted_reps', 'Assisted reps'), ('duration', 'Duration'), ('weight_duration', 'Weight and duration'), ('distance_duration', 'Distance and duration'), ('short_distance_weight', 'Distance and weight')], max_length=32)),
                ('equipment_category', models.CharField(blank=True, choices=[('none', 'None'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('plate', 'Plate'), ('resistance_band', 'Resistance band'), ('suspension', 'Suspension'), ('other', 'Other')], max_length=32)),
                ('primary_muscle', models.CharField(blank=True, choices=[('abdominals', 'Abdominals'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('glutes', 'Glutes'), ('abductors', 'Abductors'), ('adductors', 'Adductors'), ('lats', 'Lats'), ('upper_back', 'Upper back'), ('traps', 'Traps'), ('lower_back', 'Lower back'), ('chest', 'Chest'), ('cardio', 'Cardio'), ('neck', 'Neck'), ('full_body', 'Full body'), ('other', 'Other')], max_length=32)),
                ('is_custom', models.BooleanField(default=False)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='integrations.hevyaccount')),
            ],
            options={
                'ordering': ['title', 'external_id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSecondaryMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_code', models.CharField(choices=[('abdominals', 'Abdominals'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('glutes', 'Glutes'), ('abductors', 'Abductors'), ('adductors', 'Adductors'), ('lats', 'Lats'), ('upper_back', 'Upper back'), ('traps', 'Traps'), ('lower_back', 'Lower back'), ('chest', 'Chest'), ('cardio', 'Cardio'), ('neck', 'Neck'), ('full_body', 'Full body'), ('other', 'Other')], max_length=32)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscles', to='training.exercisetemplate')),
            ],
            options={
                'ordering': ['muscle_code'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_created_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('external_updated_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('provider_schema_version', models.CharField(max_length=32)),
                ('source_payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Payload hash must be a 64-character SHA-256 hex value.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='integrations.hevyaccount')),
            ],
            options={
                'ordering': ['title', 'external_id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title_snapshot', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_exercises', to='training.exercisetemplate')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.routine')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RoutineFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_created_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('external_updated_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('provider_schema_version', models.CharField(max_length=32)),
                ('source_payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Payload hash must be a 64-character SHA-256 hex value.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('external_id', models.PositiveBigIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_folders', to='integrations.hevyaccount')),
            ],
            options={
                'ordering': ['position', 'external_id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='training.routinefolder'),
        ),
        migrations.CreateModel(
            name='RoutineSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('warmup', 'Warmup'), ('normal', 'Normal'), ('failure', 'Failure'), ('dropset', 'Dropset')], max_length=16)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reps', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rep_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('rep_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('custom_metric', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.routineexercise')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_created_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('external_updated_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True, validators=[core.validators.validate_aware_datetime])),
                ('provider_schema_version', models.CharField(max_length=32)),
                ('source_payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Payload hash must be a 64-character SHA-256 hex value.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('end_time', models.DateTimeField(validators=[core.validators.validate_aware_datetime])),
                ('hevy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='integrations.hevyaccount')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='training.routine')),
            ],
            options={
                'ordering': ['-start_time', '-external_id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title_snapshot', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='training.exercisetemplate')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workout')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('warmup', 'Warmup'), ('normal', 'Normal'), ('failure', 'Failure'), ('dropset', 'Dropset')], max_length=16)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reps', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rpe', models.DecimalField(blank=True, choices=[(Decimal('6.0'), '6'), (Decimal('7.0'), '7'), (Decimal('7.5'), '7.5'), (Decimal('8.0'), '8'), (Decimal('8.5'), '8.5'), (Decimal('9.0'), '9'), (Decimal('9.5'), '9.5'), (Decimal('10.0'), '10')], decimal_places=1, max_digits=3, null=True)),
                ('custom_metric', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workoutexercise')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='exercisetemplate',
            index=models.Index(fields=['hevy_account', 'is_active'], name='exercise_template_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisetemplate',
            constraint=models.UniqueConstraint(fields=('hevy_account', 'external_id'), name='unique_exercise_template_external_id'),
        ),
        migrations.AddConstraint(
            model_name='exercisesecondarymuscle',
            constraint=models.UniqueConstraint(fields=('exercise_template', 'muscle_code'), name='unique_template_secondary_muscle'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.UniqueConstraint(fields=('routine', 'position'), name='unique_routine_exercise_position'),
        ),
        migrations.AddIndex(
            model_name='routinefolder',
            index=models.Index(fields=['hevy_account', 'is_active'], name='routine_folder_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinefolder',
            constraint=models.UniqueConstraint(fields=('hevy_account', 'external_id'), name='unique_routine_folder_external_id'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['hevy_account', 'is_active'], name='routine_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('hevy_account', 'external_id'), name='unique_routine_external_id'),
        ),
        migrations.AddConstraint(
            model_name='routineset',
            constraint=models.UniqueConstraint(fields=('routine_exercise', 'position'), name='unique_routine_set_position'),
        ),
        migrations.AddConstraint(
            model_name='routineset',
            constraint=models.CheckConstraint(condition=models.Q(('rep_range_start__isnull', True), ('rep_range_end__isnull', True), ('rep_range_start__lte', models.F('rep_range_end')), _connector='OR'), name='valid_routine_rep_range'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['hevy_account', 'start_time', 'is_active'], name='workout_account_start_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['routine', 'start_time'], name='workout_routine_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('hevy_account', 'external_id'), name='unique_workout_external_id'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='workout_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['exercise_template', 'workout'], name='workout_exercise_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'position'), name='unique_workout_exercise_position'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['set_type'], name='workout_set_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.UniqueConstraint(fields=('workout_exercise', 'position'), name='unique_workout_set_position'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('rpe__isnull', True), ('rpe__in', [Decimal('6.0'), Decimal('7.0'), Decimal('7.5'), Decimal('8.0'), Decimal('8.5'), Decimal('9.0'), Decimal('9.5'), Decimal('10.0')]), _connector='OR'), name='valid_workout_set_rpe'),
        ),
    ]
