# Generated by Django 6.0.8 on 2026-08-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetemplate',
            name='exercise_type',
            field=models.CharField(choices=[('weight_reps', 'Weight and reps'), ('reps_only', 'Reps only'), ('bodyweight_reps', 'Bodyweight reps'), ('bodyweight_assisted_reps', 'Assisted reps'), ('duration', 'Duration'), ('weight_duration', 'Weight and duration'), ('distance_duration', 'Distance and duration'), ('short_distance_weight', 'Distance and weight'), ('custom', 'Custom')], max_length=32),
        ),
    ]
