# Generated by Django 6.0.8 on 2026-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_exercisetemplate_exercise_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['workout_exercise', 'set_type'], name='workout_set_exercise_type_idx'),
        ),
    ]
