# Generated by Django 6.0.8 on 2026-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_workoutset_workout_set_exercise_type_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routine',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routinefolder',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workout',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
