# Generated by Django 6.0.8 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_exercisetemplate_raw_payload_routine_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='title_pt_br',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exercisetemplate',
            name='translation_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
